In [1]:
import tensorflow as tf

In [2]:
a = tf.constant("hello")

In [3]:
b = tf.constant("world")

In [4]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [5]:
print(result)

b'helloworld'


In [6]:
print(a)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=string>

#Operations

In [9]:
mat = tf.fill((4,4),10)

In [10]:
mat_zero = tf.zeros((4,4))

In [11]:
mat_one = tf.ones((4,4))

In [12]:
mat_rand = tf.random_normal((4,4), mean=0, stddev=1)

In [14]:
mat_randuni = tf.random_uniform((4,4),minval=0, maxval=1)

In [15]:
ops = [mat, mat_zero, mat_one, mat_rand, mat_randuni]

In [16]:
with tf.Session() as sess:
    for op in ops:
        print(sess.run(op))
        print("\n")

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[-0.2211014   1.22586107 -0.14261864  0.13017553]
 [-0.57444412 -1.58266997  1.04502141  0.49370387]
 [ 0.68522662  0.21304873 -0.55675173 -0.79823887]
 [ 0.80136061 -0.56328607  0.86884278 -2.69096828]]


[[ 0.81203067  0.27257609  0.22147942  0.26553643]
 [ 0.81554294  0.32228315  0.95660424  0.65030336]
 [ 0.5496453   0.71101177  0.31654549  0.69134092]
 [ 0.23333001  0.7550832   0.93765807  0.01295853]]




In [17]:
c = tf.constant([[1,2],[3,4]])

In [18]:
d = tf.constant([[10],[100]])

In [20]:
c.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [21]:
d.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [22]:
res = tf.matmul(c,d)

In [23]:
with tf.Session() as sess:
    print(sess.run(res))

[[210]
 [430]]


## Tensor Flow Graphs

In [24]:
print(tf.get_default_graph())

In [25]:
graph_one = tf.get_default_graph()
graph_two = tf.Graph()

In [26]:
graph_one is tf.get_default_graph()

True

In [27]:
graph_two is tf.get_default_graph()

False

In [31]:
with graph_two.as_default():
    print(graph_two is tf.get_default_graph())

True


In [32]:
graph_two is tf.get_default_graph()

False

# Variables and Placeholders

In [33]:
my_tensor = tf.random_uniform((4,4),0,1)

In [34]:
my_var = tf.Variable(initial_value=my_tensor)

In [37]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [39]:
init = tf.global_variables_initializer()

In [41]:
with tf.Session() as sess:
    init.run()
    print(sess.run(my_var))

[[ 0.07456326  0.65408039  0.62468588  0.84307981]
 [ 0.45830679  0.93151104  0.80543625  0.90353727]
 [ 0.47393167  0.35264242  0.42179751  0.9895432 ]
 [ 0.58863008  0.3436327   0.05653214  0.84180915]]


In [42]:
ph = tf.placeholder(tf.float32)

In [43]:
ph2 = tf.placeholder(tf.float64,shape=(None,4))